import Carousel from '@/components/site/layout/Carousel';
import '../styles/globals.css';
import Header from './../components/site/layout/Header';
import Footer from '@/components/site/layout/Footer';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({ children }) {
  return (
    < html lang="en " >
      <body>
        {children}
      </body>
    </html >
  )
}