import Carousel from '@/components/site/layout/Carousel';
import Footer from '@/components/site/layout/Footer';
import Header from '@/components/site/layout/Header';
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
export default function SiteLayout({ children }) {
    return (
        < html lang="en " >
            <body>
                <Header />
                <Carousel />



                {children}
                <Footer />
            </body>
        </html >
    )
}


