import Carousel from '@/components/site/layout/Carousel';
import Footer from '@/components/site/layout/Footer';
import Header from '@/components/site/layout/Header';
import Sidebar from "@/components/admin/layout/Sidebar";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
export default function SiteLayout({ children }) {
    return (
        < html lang="en " >
            <body>
                <div className="flex flex-col min-h-screen">
                    <Header />
                    <Carousel />
                    <div className="flex flex-1">
                        <aside className="w-1/4 bg-gray-600 text-white p-4 h-full">
                            <h2 className="text-2xl font-bold text-center">Admin Panel</h2>
                            <Sidebar />
                        </aside>
                        <main className="ml-1/4 w-3/4 bg-gray-500 p-4 overflow-auto">
                            <h1 className="text-xl font-bold">Dashboard LEDINHTHANG</h1>
                            {children}
                        </main>
                    </div>
                    <Footer />
                </div>
            </body>
        </html >
    )
}


